import { BoardConfig, FloorMarking, InventoryItem, MapTextAnnotation, RackBay, SafetyRule, WarehouseFacilityObject, WarehousePosition, WarehouseRack, WarehouseZone } from './types';

export const initialBoardConfig: BoardConfig = {
  companyName: 'SUNHOUSE',
  companyLogoText: 'SUNHOUSE',
  boardTitle: 'SƠ ĐỒ VẬN HÀNH & TRA CỨU KHO',
  boardSubtitle: 'HỆ THỐNG TRỰC QUAN HÓA & ĐỊNH VỊ Ô KỆ (VISUAL MANAGEMENT BOARD)',
  warehouseCode: 'NMBD',
  warehouseName: 'Nhà Máy Bình Dương - Kho Cơ Kim & Phụ Liệu',
  currentStationName: 'RACK A - BAY 02',
  currentStationCode: 'A-02',
  themeColor: '#00838f',
};

const createBays = (color: string, count: number = 5): RackBay[] => {
  return Array.from({ length: count }, (_, i) => ({
    id: String(i + 1).padStart(2, '0'),
    bayNumber: String(i + 1).padStart(2, '0'),
    tiers: 3, // Chuẩn 3 tầng (A: Vàng, B: Xanh, C: Đỏ)
    slotsPerTier: 2,
    color: color,
    fillLevel: 70 + Math.floor(Math.random() * 25),
  }));
};

export const defaultRacks: WarehouseRack[] = [
  // 1. LEFT SIDE - 3 Long Selective Pallet Racks (Mỗi kệ 5 khoang, 3 tầng)
  {
    id: 'A',
    name: 'DÃY 01 (Kệ Dài A - Sát Tường Trái)',
    colorName: 'DÃY 01 (Kệ Trái 1)',
    color: '#ea580c',
    x: 8,
    y: 10,
    length: 5, // Tự động 5 khoang chuẩn
    bayLength: 4.8,
    width: 2.8,
    bays: createBays('#ea580c', 5),
    category: 'Thùng Carton & Phụ liệu cơ kim',
  },
  {
    id: 'B',
    name: 'DÃY 02 (Kệ Dài B - Giữa Trái)',
    colorName: 'DÃY 02 (Kệ Trái 2)',
    color: '#ea580c',
    x: 16,
    y: 10,
    length: 5,
    bayLength: 4.8,
    width: 2.8,
    bays: createBays('#ea580c', 5),
    category: 'Thùng Linh kiện & Phụ kiện dập',
  },
  {
    id: 'C',
    name: 'DÃY 03 (Kệ Dài C - Phải Trái)',
    colorName: 'DÃY 03 (Kệ Trái 3)',
    color: '#ea580c',
    x: 24,
    y: 10,
    length: 5,
    bayLength: 4.8,
    width: 2.8,
    bays: createBays('#ea580c', 5),
    category: 'Mâm nhiệt nồi cơm & Linh kiện ấm điện',
  },

  // 2. CENTER TOP - 2 Blocks of Double Pallet Racks (Mỗi kệ 5 khoang, 3 tầng)
  // Block 1 (Dãy D & E)
  {
    id: 'D',
    name: 'DÃY 04 (Kệ Đôi D1 - Trung Tâm)',
    colorName: 'DÃY 04 (Cụm 1 - Kệ 1)',
    color: '#ea580c',
    x: 35,
    y: 6,
    length: 5,
    bayLength: 4.8,
    width: 2.8,
    bays: createBays('#ea580c', 5),
    category: 'Linh kiện điện tử & Rơ-le cảm biến',
  },
  {
    id: 'E',
    name: 'DÃY 05 (Kệ Đôi E1 - Trung Tâm)',
    colorName: 'DÃY 05 (Cụm 1 - Kệ 2)',
    color: '#ea580c',
    x: 39,
    y: 6,
    length: 5,
    bayLength: 4.8,
    width: 2.8,
    bays: createBays('#ea580c', 5),
    category: 'Thân vỏ ấm siêu tốc & Chảo dập',
  },
  // Block 2 (Dãy F & G)
  {
    id: 'F',
    name: 'DÃY 06 (Kệ Đôi F2 - Phía Sau)',
    colorName: 'DÃY 06 (Cụm 2 - Kệ 1)',
    color: '#ea580c',
    x: 48,
    y: 6,
    length: 5,
    bayLength: 4.8,
    width: 2.8,
    bays: createBays('#ea580c', 5),
    category: 'Tay cầm Bakelite & Nắp kính cường lực',
  },
  {
    id: 'G',
    name: 'DÃY 07 (Kệ Đôi G2 - Phía Sau)',
    colorName: 'DÃY 07 (Cụm 2 - Kệ 2)',
    color: '#ea580c',
    x: 52,
    y: 6,
    length: 5,
    bayLength: 4.8,
    width: 2.8,
    bays: createBays('#ea580c', 5),
    category: 'Dây nguồn & Cụm công tắc gia nhiệt',
  },

  // 3. CENTER BOTTOM - Staging Racks & Tote Bins (2 Dãy Kệ Ngắn Trung Tâm Phía Trước)
  {
    id: 'H',
    name: 'DÃY 08 (Kệ Hàng H - Khay Đen & Carton)',
    colorName: 'DÃY 08 (Phía trước 1)',
    color: '#ea580c',
    x: 27,
    y: 56,
    length: 5,
    bayLength: 4.0,
    width: 2.8,
    bays: createBays('#ea580c', 5),
    category: 'Khay linh kiện đen & Thùng carton đóng gói',
  },
  {
    id: 'I',
    name: 'DÃY 09 (Kệ Hàng I - Khay Đen & Carton)',
    colorName: 'DÃY 09 (Phía trước 2)',
    color: '#ea580c',
    x: 33,
    y: 56,
    length: 5,
    bayLength: 4.0,
    width: 2.8,
    bays: createBays('#ea580c', 5),
    category: 'Khay linh kiện đen & Bao bì đóng thùng',
  },
];

export const defaultAnnotations: MapTextAnnotation[] = [
  {
    id: 'ann-1',
    textVi: 'DÃY KỆ KIM LOẠI',
    textEn: 'METAL RACK ROW',
    x: 16,
    y: 2,
    z: 60,
    fontSize: 12,
    color: '#0f172a',
  },
  {
    id: 'ann-2',
    textVi: 'LỐI ĐI 5S',
    textEn: 'MAIN AISLE',
    x: 74,
    y: 4,
    z: 45,
    fontSize: 11,
    color: '#0f172a',
    badge5s: '5S',
  },
  {
    id: 'ann-3',
    textVi: 'KHU VỰC ĐÓNG GÓI',
    textEn: 'PACKING AREA',
    x: 8,
    y: 70,
    z: 0,
    fontSize: 12,
    color: '#0f172a',
  },
  {
    id: 'ann-4',
    textVi: 'BỘ PHẬN GIAO HÀNG',
    textEn: 'DELIVERY DEPT',
    x: 82,
    y: 70,
    z: 0,
    fontSize: 12,
    color: '#0f172a',
  },
  {
    id: 'ann-5',
    textVi: 'LỐI ĐI CHÍNH',
    textEn: 'MAIN AISLE',
    x: 48,
    y: 50,
    z: 0,
    fontSize: 11,
    color: '#0f172a',
    rotation: -15,
  },
];

export const defaultFloorMarkings: FloorMarking[] = [
  {
    id: 'fm-1',
    name: 'Vạch bao 3 Dãy Kệ Trái',
    type: 'box',
    x: 5,
    y: 6,
    width: 24,
    length: 34,
    color: '#facc15',
    strokeWidth: 2.8,
    fillOpacity: 0.05,
  },
  {
    id: 'fm-2',
    name: 'Vạch bao 2 Cụm Kệ Giữa',
    type: 'box',
    x: 32,
    y: 4,
    width: 24,
    length: 30,
    color: '#facc15',
    strokeWidth: 2.8,
    fillOpacity: 0.05,
  },
  {
    id: 'fm-3',
    name: 'Vạch bao Kệ Trước & Khay Đen',
    type: 'box',
    x: 24,
    y: 52,
    width: 14,
    length: 24,
    color: '#facc15',
    strokeWidth: 2.8,
    fillOpacity: 0.05,
  },
  {
    id: 'fm-4',
    name: 'Vạch bao Sàn Gác Lửng',
    type: 'box',
    x: 64,
    y: 42,
    width: 28,
    length: 22,
    color: '#facc15',
    strokeWidth: 2.8,
    fillOpacity: 0.05,
  },
  {
    id: 'fm-5',
    name: 'Vạch chỉ dẫn Lối Đi Chính 5S',
    type: 'line',
    x: 48,
    y: 36,
    x2: 48,
    y2: 78,
    color: '#facc15',
    strokeWidth: 3.5,
    fillOpacity: 0,
  },
];

export const defaultZones: WarehouseZone[] = [
  {
    id: 'mezzanine',
    name: 'SÀN GÁC LỬNG & MÁI CHE TRẮNG MEZZANINE',
    nameEn: 'WHITE CANOPY & MEZZANINE AUTOMATION PLATFORM',
    type: 'office',
    color: '#f8fafc',
    x: 68,
    y: 46,
    width: 36,
    height: 16,
    icon: 'Layers',
  },
  {
    id: 'blue_containers',
    name: 'KHU MODULE THÙNG CHỨA XANH (BLUE CONTAINERS)',
    nameEn: 'BLUE STORAGE CONTAINER CELLS',
    type: 'storage',
    color: '#2563eb',
    x: 82,
    y: 46,
    width: 16,
    height: 12,
    icon: 'Boxes',
  },
  {
    id: 'sorting_conveyors',
    name: 'KHU KỆ PHÂN LOẠI & DÂY CHUYỀN BĂNG TẢI',
    nameEn: 'FLOW RACKS & CONVEYOR SYSTEM',
    type: 'packing',
    color: '#334155',
    x: 68,
    y: 66,
    width: 34,
    height: 18,
    icon: 'Package',
  },
  {
    id: 'green_planters',
    name: 'DẢI TIỂU CẢNH CÂY XANH 5S (GREEN PLANTS)',
    nameEn: '5S GREENERY & ECO PLANT STRIP',
    type: 'aisle',
    color: '#22c55e',
    x: 74,
    y: 84,
    width: 32,
    height: 6,
    icon: 'Sparkles',
  },
];

export const defaultFacilities: WarehouseFacilityObject[] = [
  // 1. White Elevated Mezzanine Canopy (Sàn Mái Che Trắng)
  {
    id: 'mezzanine-1',
    name: 'Sàn Gác Lửng & Mái Che Trắng Mezzanine',
    type: 'mezzanine',
    x: 68,
    y: 46,
    width: 38,
    length: 16,
    height: 28,
    color: '#f8fafc',
    category: 'Kết cấu sàn tầng lửng',
    hasStairs: true,
    notes: 'Sàn mái che trắng kiến trúc hiện đại, khung thép chịu lực',
  },
  // 2. Blue Storage Containers / Shuttle Modules (Cụm Thùng Chứa Xanh)
  {
    id: 'blue-containers-1',
    name: 'Cụm Module Thùng Chứa Xanh Công Nghiệp',
    type: 'pallet_staging',
    x: 84,
    y: 46,
    width: 14,
    length: 14,
    height: 8,
    boxCols: 2,
    boxRows: 4,
    boxHeight: 8,
    color: '#2563eb',
    category: 'Module thùng chứa tự động',
    notes: 'Khối thùng chứa xanh chuẩn công nghiệp',
  },
  // 3. Gravity Flow Shelves & Sorting Racks (Kệ Phân Loại Khay Đen)
  {
    id: 'flow-racks-1',
    name: 'Cụm Kệ Trượt Phân Loại Khay Đen #01',
    type: 'pallet_staging',
    x: 66,
    y: 64,
    width: 10,
    length: 12,
    height: 6,
    boxCols: 2,
    boxRows: 5,
    boxHeight: 5,
    color: '#1e293b',
    category: 'Kệ trượt phân loại linh kiện',
    notes: 'Kệ phân tầng chứa khay đen công nghiệp',
  },
  {
    id: 'flow-racks-2',
    name: 'Cụm Kệ Trượt Phân Loại Khay Đen #02',
    type: 'pallet_staging',
    x: 74,
    y: 72,
    width: 10,
    length: 12,
    height: 6,
    boxCols: 2,
    boxRows: 5,
    boxHeight: 5,
    color: '#1e293b',
    category: 'Kệ trượt phân loại linh kiện',
    notes: 'Kệ phân tầng chứa khay đen công nghiệp',
  },
  // 4. Conveyor Lines & Automation (Dây chuyền tự động góc trên phải)
  {
    id: 'conveyor-1',
    name: 'Dây Chuyền Băng Tải & Trạm Lắp Ráp Tự Động',
    type: 'conveyor',
    x: 82,
    y: 18,
    width: 26,
    length: 16,
    height: 10,
    laneCount: 3,
    totesPerLane: 6,
    color: '#475569',
    category: 'Hệ thống tự động hóa',
    notes: 'Băng chuyền con lăn & bàn thao tác kỹ thuật có rào an toàn vàng',
  },
  // 5. Workstations (Bàn kỹ thuật phía trên)
  {
    id: 'workstation-1',
    name: 'Trạm Lắp Ráp & Kiểm Định Kỹ Thuật',
    type: 'workstation',
    x: 86,
    y: 30,
    width: 8,
    length: 5,
    height: 8,
    color: '#64748b',
    category: 'Trạm thao tác công nhân',
    notes: 'Bàn thao tác kỹ thuật & giá lắp ráp',
  },
  // 6. Planters along bottom right wall (Dải tiểu cảnh xanh 5S)
  {
    id: 'planter-1',
    name: 'Bồn Cây Cảnh Quan & Cụm Xanh 5S',
    type: 'planter',
    x: 76,
    y: 86,
    width: 24,
    length: 4,
    height: 6,
    color: '#15803d',
    category: 'Cảnh quan 5S xanh sạch',
    notes: 'Hàng bồn cây cảnh quan xanh 5S dọc lối đi',
  },
];

export const defaultPositions: WarehousePosition[] = [
  {
    x: 24,
    y: 20,
    label: 'Kệ A - Bay 02 (Đầu Dãy 01)',
    rackId: 'A',
    bayId: '02',
    tier: 3,
    slot: 2,
  },
  {
    x: 35,
    y: 18,
    label: 'Kệ C - Bay 03 (Dãy 03 Đôi)',
    rackId: 'C',
    bayId: '03',
    tier: 2,
    slot: 1,
  },
  {
    x: 48,
    y: 16,
    label: 'Kệ D - Bay 04 (Dãy 04 Đôi)',
    rackId: 'D',
    bayId: '04',
    tier: 1,
    slot: 2,
  },
  {
    x: 61,
    y: 14,
    label: 'Kệ F - Bay 02 (Dãy 06 Đôi)',
    rackId: 'F',
    bayId: '02',
    tier: 4,
    slot: 1,
  },
  {
    x: 14,
    y: 44,
    label: 'Kệ J - Bay 02 (Kệ Ngắn Phía Trước)',
    rackId: 'J',
    bayId: '02',
    tier: 2,
    slot: 2,
  },
  {
    x: 28,
    y: 48,
    label: 'Khu Tập Kết Pallet Thùng Carton',
    zoneId: 'pallet_staging',
  },
  {
    x: 58,
    y: 46,
    label: 'Sàn Gác Lửng Mezzanine (Lối Lên Cầu Thang)',
    zoneId: 'mezzanine',
  },
  {
    x: 64,
    y: 68,
    label: 'Dây Chuyền Băng Tải & Khay Nhựa Xanh (Làn AGV)',
    zoneId: 'conveyor_lanes',
  },
  {
    x: 42,
    y: 35,
    label: 'Ngã Tư Lối Đi Chính Xe Nâng',
  },
];

export const defaultItems: InventoryItem[] = [
  {
    id: 'item-001',
    code: '001',
    name: 'Bulong M6x20',
    category: 'Bulong - Ốc vít',
    location: 'A-02-3-2',
    rackId: 'A',
    bayId: '02',
    tier: 3,
    slot: 2,
    direction: '↑',
    spec: 'Thép mạ kẽm trắng - Ren mịn',
    unit: 'Hộp (500 cái)',
    quantity: 45,
    minQuantity: 10,
    status: 'in_stock',
    barcode: '8936012300101',
    updatedAt: '2026-08-19 14:30',
    note: 'Sử dụng cho dây chuyền lắp ráp nắp nồi cơm SHD-860',
  },
  {
    id: 'item-002',
    code: '002',
    name: 'Bulong M8x20',
    category: 'Bulong - Ốc vít',
    location: 'A-02-1-2',
    rackId: 'A',
    bayId: '02',
    tier: 1,
    slot: 2,
    direction: '↑',
    spec: 'Inox 304 không gỉ',
    unit: 'Hộp (250 cái)',
    quantity: 32,
    minQuantity: 8,
    status: 'in_stock',
    barcode: '8936012300102',
    updatedAt: '2026-08-18 09:15',
  },
  {
    id: 'item-003',
    code: '003',
    name: 'Bulong M8x25',
    category: 'Bulong - Ốc vít',
    location: 'A-02-1-1',
    rackId: 'A',
    bayId: '02',
    tier: 1,
    slot: 1,
    direction: '↑',
    spec: 'Thép cường độ cao 8.8',
    unit: 'Hộp (250 cái)',
    quantity: 18,
    minQuantity: 10,
    status: 'in_stock',
    barcode: '8936012300103',
    updatedAt: '2026-08-19 11:20',
  },
  {
    id: 'item-004',
    code: '004',
    name: 'Bulong M6x12',
    category: 'Bulong - Ốc vít',
    location: 'A-02-2-1',
    rackId: 'A',
    bayId: '02',
    tier: 2,
    slot: 1,
    direction: '↑',
    spec: 'Đầu tròn khía chữ thập',
    unit: 'Hộp (1,000 cái)',
    quantity: 60,
    minQuantity: 15,
    status: 'in_stock',
    barcode: '8936012300104',
    updatedAt: '2026-08-17 16:45',
  },
  {
    id: 'item-005',
    code: '005',
    name: 'Bulong M8x30',
    category: 'Bulong - Ốc vít',
    location: 'A-02-2-2',
    rackId: 'A',
    bayId: '02',
    tier: 2,
    slot: 2,
    direction: '↑',
    spec: 'Mạ kẽm nhúng nóng',
    unit: 'Hộp (200 cái)',
    quantity: 12,
    minQuantity: 10,
    status: 'in_stock',
    barcode: '8936012300105',
    updatedAt: '2026-08-19 08:00',
  },
  {
    id: 'item-006',
    code: '006',
    name: 'Bulong M10x20',
    category: 'Bulong - Ốc vít',
    location: 'A-03-2-2',
    rackId: 'A',
    bayId: '03',
    tier: 2,
    slot: 2,
    direction: '→',
    spec: 'Đầu lục giác ngoài',
    unit: 'Bao (100 cái)',
    quantity: 5,
    minQuantity: 10,
    status: 'low_stock',
    barcode: '8936012300106',
    updatedAt: '2026-08-19 13:10',
  },
  {
    id: 'item-007',
    code: '007',
    name: 'Bulong M10x25',
    category: 'Bulong - Ốc vít',
    location: 'A-03-2-1',
    rackId: 'A',
    bayId: '03',
    tier: 2,
    slot: 1,
    direction: '→',
    spec: 'Đầu lục giác ngoài M10',
    unit: 'Bao (100 cái)',
    quantity: 24,
    minQuantity: 5,
    status: 'in_stock',
    barcode: '8936012300107',
    updatedAt: '2026-08-18 10:00',
  },
  {
    id: 'item-008',
    code: '008',
    name: 'Bulong M10x30',
    category: 'Bulong - Ốc vít',
    location: 'A-03-3-1',
    rackId: 'A',
    bayId: '03',
    tier: 3,
    slot: 1,
    direction: '→',
    spec: 'Ren suốt chiều dài 30mm',
    unit: 'Bao (100 cái)',
    quantity: 0,
    minQuantity: 5,
    status: 'out_of_stock',
    barcode: '8936012300108',
    updatedAt: '2026-08-19 09:30',
  },
  {
    id: 'item-009',
    code: '009',
    name: 'Bulong M12x25',
    category: 'Bulong - Ốc vít',
    location: 'A-04-1-2',
    rackId: 'A',
    bayId: '04',
    tier: 1,
    slot: 2,
    direction: '↑',
    spec: 'Bulong neo chịu tải',
    unit: 'Thùng (50 cái)',
    quantity: 15,
    minQuantity: 4,
    status: 'in_stock',
    barcode: '8936012300109',
    updatedAt: '2026-08-16 14:00',
  },
  {
    id: 'item-010',
    code: '010',
    name: 'Bulong M12x30',
    category: 'Bulong - Ốc vít',
    location: 'A-04-2-1',
    rackId: 'A',
    bayId: '04',
    tier: 2,
    slot: 1,
    direction: '↑',
    spec: 'Ren lửng thép đen',
    unit: 'Thùng (50 cái)',
    quantity: 28,
    minQuantity: 6,
    status: 'in_stock',
    barcode: '8936012300110',
    updatedAt: '2026-08-18 15:30',
  },
  {
    id: 'item-011',
    code: '011',
    name: 'Bulong M16x40',
    category: 'Bulong - Ốc vít',
    location: 'A-05-3-1',
    rackId: 'A',
    bayId: '05',
    tier: 3,
    slot: 1,
    direction: '↑',
    spec: 'Bulong khung bệ máy dập',
    unit: 'Kiện (20 cái)',
    quantity: 9,
    minQuantity: 3,
    status: 'in_stock',
    barcode: '8936012300111',
    updatedAt: '2026-08-15 11:00',
  },
  {
    id: 'item-012',
    code: '012',
    name: 'Mâm Nhiệt Nồi Cơm 1.8L',
    category: 'Linh kiện gia nhiệt',
    location: 'B-03-2-1',
    rackId: 'B',
    bayId: '03',
    tier: 2,
    slot: 1,
    direction: '↑',
    spec: 'Công suất 700W - 220V Ø190mm',
    unit: 'Thùng (30 cái)',
    quantity: 120,
    minQuantity: 30,
    status: 'in_stock',
    barcode: '8936012300201',
    updatedAt: '2026-08-19 16:00',
  },
  {
    id: 'item-013',
    code: '013',
    name: 'Đai Ốc Khóa M8 Inox',
    category: 'Đai ốc - Vòng đệm',
    location: 'A-02-4-1',
    rackId: 'A',
    bayId: '02',
    tier: 4,
    slot: 1,
    direction: '↑',
    spec: 'Có vòng đệm nylon chống rung',
    unit: 'Hộp (500 cái)',
    quantity: 35,
    minQuantity: 10,
    status: 'in_stock',
    barcode: '8936012300113',
    updatedAt: '2026-08-19 10:45',
  },
  {
    id: 'item-014',
    code: '014',
    name: 'Vỏ Thân Nồi Inox SHD-28',
    category: 'Vỏ kim loại',
    location: 'C-04-1-1',
    rackId: 'C',
    bayId: '04',
    tier: 1,
    slot: 1,
    direction: '↑',
    spec: 'Inox 430 dập hoa văn bóng',
    unit: 'Pallet (200 cái)',
    quantity: 14,
    minQuantity: 5,
    status: 'in_stock',
    barcode: '8936012300301',
    updatedAt: '2026-08-19 08:30',
  },
  {
    id: 'item-015',
    code: '015',
    name: 'Cảm Biến Nhiệt Rơ-le KSD301',
    category: 'Linh kiện điện trở',
    location: 'D-02-3-2',
    rackId: 'D',
    bayId: '02',
    tier: 3,
    slot: 2,
    direction: '↑',
    spec: '160°C - 10A 250V chân cong',
    unit: 'Hộp (100 cái)',
    quantity: 85,
    minQuantity: 20,
    status: 'in_stock',
    barcode: '8936012300401',
    updatedAt: '2026-08-17 14:15',
  },
  {
    id: 'item-016',
    code: '016',
    name: 'Tay Cầm Cách Nhiệt Bakelite',
    category: 'Linh kiện nhựa đúc',
    location: 'E-03-2-1',
    rackId: 'E',
    bayId: '03',
    tier: 2,
    slot: 1,
    direction: '↑',
    spec: 'Chịu nhiệt 220°C kèm ốc ren',
    unit: 'Thùng (150 cặp)',
    quantity: 42,
    minQuantity: 15,
    status: 'in_stock',
    barcode: '8936012300501',
    updatedAt: '2026-08-18 11:30',
  },
];

export const defaultSafetyRules: SafetyRule[] = [
  {
    id: 'r1',
    title: 'GIỮ VỆ SINH CHUNG',
    description: 'Rác thải để đúng nơi quy định, quét dọn lối đi thông thoáng cuối ca làm.',
    icon: 'Trash2',
    category: '5S',
  },
  {
    id: 'r2',
    title: 'TUÂN THỦ 5S TOÀN DIỆN',
    description: 'Sàng lọc - Sắp xếp - Sạch sẽ - Săn sóc - Sẵn sàng mọi lúc.',
    icon: 'Sparkles',
    category: '5S',
  },
  {
    id: 'r3',
    title: 'KHÔNG LẬP HÀNG TRÀN RA LỐI ĐI',
    description: 'Pallet và hàng hóa không vượt quá vạch vàng an toàn lối đi chính.',
    icon: 'AlertTriangle',
    category: 'AN TOÀN',
  },
  {
    id: 'r4',
    title: 'AN TOÀN PCCC & LỐI THOÁT HIỂM',
    description: 'Không che chắn tủ chữa cháy, bình CO2, cửa thoát nạn. Cấm hút thuốc.',
    icon: 'Flame',
    category: 'PCCC',
  },
  {
    id: 'r5',
    title: 'KHÔNG LẬP BÀN KM HASH LIÊN',
    description: 'Không lập bàn phụ hoặc đồ vật tạm bợ gây mất đồng bộ luồng di chuyển.',
    icon: 'ShieldBan',
    category: 'AN TOÀN',
  },
  {
    id: 'r6',
    title: 'SẮP XẾP ĐÚNG Ô KỆ (SLOTTING)',
    description: 'Hàng nặng để tầng dưới (T1-T2), hàng nhẹ để tầng cao (T3-T4).',
    icon: 'Layers',
    category: '5S',
  },
];
